sudo: required
services:
  - docker

before_install:
  - docker build -t krishnakotadocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true krishnakotadocker/react-test npm run test

after_success:
  - docker build -t krishnakotadocker/multi-client ./client
  - docker build -t krishnakotadocker/multi-server ./server
  - docker build -t krishnakotadocker/multi-worker ./worker
  - docker build -t krishnakotadocker/multi-nginx ./nginx
  # docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # docker push
  - docker push krishnakotadocker/multi-client
  - docker push krishnakotadocker/multi-server
  - docker push krishnakotadocker/multi-worker
  - docker push krishnakotadocker/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-container"
  env: "MultiContainer-env"
  bucket_name: "elasticbeanstalk-ap-south-1-898404873516"
  bucket_path: "container-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
